services:
  switchradar:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "80"
    restart: always
    volumes:
      - switchradar_data:/app/data

volumes:
  switchradar_data:
    driver: local
